[tool.poetry]
name = "many"
version = "0.1.0"
description = ""
authors = ["Kevin Hu <kevinhuwest@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6.1"
numpy = "^1.19.1"
pandas = "^1.1.0"
scipy = "^1.5.2"
statsmodels = "^0.11.1"
tqdm = "^4.48.2"
matplotlib = "^3.3.0"
seaborn = "^0.10.1"
sklearn = "^0.0"
adjusttext = "^0.7.3"
pre-commit = "^2.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
